### PR TITLE
Validate `first_step` and `max_accel` parameters values in `login_solve` and related functions

### PR DESCRIPTION
**Pull request by lusimeon**
see #459

### CODE REVIEW

**Comment by tturocy** [comment]
Thank you for this.  Could you also please consider adding a few tests to check these, and also to check the `maxregret` parameter?  We acknowledge that the test suite does not yet include confirming that errors are thrown on bad arguments, but these issues are part of the process of doing that.

Also, while you are at it, the function names quoted in `logit_solve_branch` and `logit_solve_lambda` aren't correct, so if you could clean those up as well this would be super useful.

**Comment by lusimeon** [comment]
Hi, thank you for your feedback. I've added tests to checks parameters, and correct the mispelled functions names. Seems good for you?

**Comment by tturocy** [comment]
Thank you - apologies that it has taken so long to come back around to this.

I see only one minor item, which is that the inequality on the test for `max_accel` is inconsistent - sometimes it's weak, sometimes it's strict.  A value of 1.0 is valid for the parameter, so the strict inequality `< 1` would be the correct one.

**Comment by tturocy** [comment]
Merged into `master` at ad47d5443 with many thanks.

**Pull request closed without merging**
