### PR TITLE
Update and rename INSTALL and README to Markdown files (.md)

### PR DESCRIPTION
**Pull request by EwoutH**
Formats the INSTALL file as a markdown file, which increases readability.

### CODE REVIEW

**Comment by tturocy** [comment]
This is a good idea.  But I think we need at least to add the foreign option for automake, otherwise it will start complaining about INSTALL being missing.

And if we're going to do this, should also consider doing README -> README.md at the same time for consistency?

**Comment by tturocy** [comment]
The AM_INIT_AUTOMAKE options are just separated by a space, not a comma.

If you remove the comma between subdir-objects and foreign, and then do a rebase/squash into one commit, I'll gladly merge.

**Comment by EwoutH** [comment]
Good catch, fixed it.

I don’t have a computer at hand, but feel free to Squash and merge via the GitHub interface. Otherwise I can clean it up tomorrow.

**Comment by EwoutH** [comment]
Rebased, reset and recommitted!

**Pull request merged**
